version: 2.0
jobs:
  build:
    docker:
    - image: typelead/eta:latest
    environment:
      JAVA_OPTS: -Xmx1G -Xms1G
    steps:
    - checkout
    - run: ./init.sh
    - run:
        name: Fast Benchmarks
        command: ./fast-benchmarks.sh
        no_output_timeout: 1h
    - run:
        name: Slow Benchmarks
        command: ./slow-benchmarks.sh
        no_output_timeout: 1h

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
